# Generated by Django 2.1.2 on 2019-11-21 04:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=1000)),
                ('second', models.CharField(max_length=1000)),
                ('operator', models.CharField(max_length=1)),
                ('result', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Calcuation',
        ),
    ]
