# Generated by Django 2.1.2 on 2019-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20191120_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='timeCreated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
